name: Deploy
# Deploy sphinx documentation to GitHub Pages in docs branch

on:
    # Triggers the workflow on push or pull request events but only for the "main" branch
    push:
        branches: [ "main" ]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            # Checkout the repository
            - name: Checkout repository
              uses: actions/checkout@v2
            # Update pip
            - name: Update pip
              run: pip install --upgrade pip
            # Install the dependencies
            - name: Install dependencies
              run: pip install -r docs/requirements.txt
            # Install bt_tools
            # Set up ROS
            - name: Set up ROS
              uses: ros-tooling/setup-ros@v0.7
              with:
                required-ros-distributions: humble
            # Get bt_tools TODO: remove after the release of bt_tools
            - name: Checkout bt_tools
              uses: actions/checkout@v2
              with:
                repository: boschresearch/bt_tools
                ref: main
                path: colcon_ws/src/bt_tools
            # Compile bt_tools TODO: remove after the release of bt_tools
            - name: Compile bt_tools
              run: |
                source /opt/ros/humble/setup.bash
                # Install dependencies
                cd colcon_ws
                rosdep update && rosdep install --from-paths src --ignore-src -y
                # Build and install bt_tools
                colcon build --symlink-install
            # Install packages
            - name: Install our packages
              run: |
                    source colcon_ws/install/setup.bash
                    pip install .
            # build the documentation
            - name: Build documentation
              run: |
                    source colcon_ws/install/setup.bash
                    cd docs
                    make html
            # upload the documentation to GitHub Pages
            - name: Upload artifact
              uses: actions/upload-pages-artifact@v3
              with:
                    path: docs/build/html
    deploy:
        # Add a dependency to the build job
        needs: build

        # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
        permissions:
            pages: write      # to deploy to Pages
            id-token: write   # to verify the deployment originates from an appropriate source

        # Deploy to the github-pages environment
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}

        runs-on: ubuntu-latest

        steps:
            # deploy the documentation to GitHub Pages
            - name: Deploy to github pages
              id: deployment
              uses: actions/deploy-pages@v4
