name: Test
# Test the python packages that are part of the toolchain

on:
    push:
        branches: [ "main" ]
    pull_request:

jobs:
    test:
        strategy:
            matrix:
                include:
                  - ros-distro: jazzy
                  - ros-distro: humble
            fail-fast: false
        runs-on: ubuntu-latest
        container:
          image: ros:${{ matrix.ros-distro }}
        steps:
            # Checkout the repository
            - name: Checkout repository
              uses: actions/checkout@v2
            # Set up ROS
            # - name: Set up ROS
            #   uses: ros-tooling/setup-ros@0.7.15
            #   with:
            #     required-ros-distributions: ${{ matrix.ros-distro }}
            # Install missing packages in docker
            - name: Docker APT packages installation
              id: docker_pkg_install_apt_packages
              run: apt update && apt install -y wget python3-pip
            # Get smc_storm for testing
            - name: Get smc_storm
              id: get_smc_storm
              run: |
                wget https://github.com/convince-project/smc_storm/releases/latest/download/smc_storm_executable.tar.gz
                tar -xzf smc_storm_executable.tar.gz
                ./install.sh --install-dependencies
                # Save the path to the smc_storm executable
                echo SMC_STORM_PATH=$PWD/bin/ >> $GITHUB_OUTPUT
            # Update pip
            - name: Update pip
              run: python3 -m pip install --upgrade pip
              if: ${{ matrix.ros-distro == 'humble' }}
            # install the packages
            - name: Install packages
              run: |
                python3 -m pip install ${{ matrix.ros-distro == 'jazzy' && '--break-system-packages' || '' }} .[dev]
            # lint packages
            # TODO: add linting
            # Prepare ROS WS for the tests
            - name: Install ROS support pkgs
              run: |
                source /opt/ros/${{ matrix.ros-distro }}/setup.bash
                mkdir ros_interfaces_ws
                cd ros_interfaces_ws
                ln -s ../ros_support_interfaces src
                rosdep update
                rosdep install --from-paths src -y --ignore-src
                colcon build --cmake-args -DCMAKE_BUILD_TYPE=Release
              shell: bash
            # run the tests
            - name: Run tests
              run: |
                export PATH=$PATH:${{ steps.get_smc_storm.outputs.SMC_STORM_PATH }}
                source ros_interfaces_ws/install/setup.bash
                pytest-3 -vs .
              shell: bash
